{
 "title": "Lab 3 Simple Dashboard",
 "tags": [
  "lab3",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "Prometheus Status"
    }
   ]
  },
  {
   "title": "Windows CPU User Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(windows_cpu_time_total{mode=\"user\", job=\"windows\"}[5m])",
     "legendFormat": "CPU User Time"
    }
   ]
  },
  {
   "title": "API Latency (P95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"fastapi\"}[5m])) by (le))",
     "legendFormat": "API Latency P95"
    }
   ]
  }
 ]
}