global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "windows"
    static_configs:
      - targets: ["host.docker.internal:9182"]
        labels:
          app: "windows"
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]
        labels:
          app: "fastapi"